#route:
#  group_by: ['alertname']
#  group_wait: 30s
#  group_interval: 5m
#  repeat_interval: 1h
#  receiver: 'email'
#receivers:
#  - name: email
#    email_configs:
#      - to: pushpakvattam@gmail.com
#        from: pushpakvattam@gmail.com
#        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
#        auth_username: "{{ lookup('amazon.aws.aws_ssm', 'ses-username', region='us-east-1' ) }}"
#        auth_password: "{{ lookup('amazon.aws.aws_ssm', 'ses-password', region='us-east-1' ) }}"
#        require_tls: true
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
#
global:
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
  smtp_from: 'pushpakvattam@gmail.com'
  smtp_auth_username: "{{ lookup('amazon.aws.aws_ssm', 'ses-username', region='us-east-1' ) }}"
  smtp_auth_password: "{{ lookup('amazon.aws.aws_ssm', 'ses-password', region='us-east-1' ) }}"
  smtp_require_tls: true
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'pushpakvattam@gmail.com'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
